version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - frontend
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html/wp-content
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  db-backup:
    image: mysql:latest
    command: sleep infinity
    volumes:
      - ./db_backups:/db_backups
    networks:
      - backend

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail
    domainname: ${MAIL_DOMAIN_NAME}
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      - ENABLE_SPAMASSASSIN=${MAIL_ENABLE_SPAMASSASSIN}
      - ENABLE_CLAMAV=${MAIL_ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${MAIL_ENABLE_FAIL2BAN}
    networks:
      - frontend
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  npm_data:
  npm_letsencrypt:
  db_data:
  wordpress_data:
  maildata:
  mailstate:
  maillogs:

networks:
  frontend:
  backend:
